/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyCreditsRouteImport } from './routes/buy-credits'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarnCreditsRouteImport } from './routes/earn-credits'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TiktokSongFinderRouteImport } from './routes/tiktok-song-finder'
import { Route as ToolReferenceRouteImport } from './routes/tool-reference'
import { Route as ToolReferenceUploadRouteImport } from './routes/tool-reference-upload'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiRecognizeRouteImport } from './routes/api.recognize'
import { Route as BillingReturnRouteImport } from './routes/billing.return'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminRecognitionsIndexRouteImport } from './routes/admin.recognitions.index'
import { Route as AdminRecognitionsAttemptIdRouteImport } from './routes/admin.recognitions.$attemptId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as ApiAdminSplatRouteImport } from './routes/api.admin.$'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiBillingCatalogRouteImport } from './routes/api.billing.catalog'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api.billing.checkout'
import { Route as ApiBillingOrderRouteImport } from './routes/api.billing.order'
import { Route as ApiBillingOrdersRouteImport } from './routes/api.billing.orders'
import { Route as ApiBillingReconcileRouteImport } from './routes/api.billing.reconcile'
import { Route as ApiBillingWebhookRouteImport } from './routes/api.billing.webhook'
import { Route as ApiRecognitionStatusRouteImport } from './routes/api.recognition.status'
import { Route as ApiRewardsShareRouteImport } from './routes/api.rewards.share'
import { Route as ApiSandboxSessionRouteImport } from './routes/api.sandbox.session'
import { Route as ApiTiktokPocRouteImport } from './routes/api.tiktok.poc'
import { Route as ApiTiktokRecognizeRouteImport } from './routes/api.tiktok.recognize'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api.auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCreditsRoute = BuyCreditsRouteImport.update({
  id: '/buy-credits',
  path: '/buy-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnCreditsRoute = EarnCreditsRouteImport.update({
  id: '/earn-credits',
  path: '/earn-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokSongFinderRoute = TiktokSongFinderRouteImport.update({
  id: '/tiktok-song-finder',
  path: '/tiktok-song-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolReferenceRoute = ToolReferenceRouteImport.update({
  id: '/tool-reference',
  path: '/tool-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolReferenceUploadRoute = ToolReferenceUploadRouteImport.update({
  id: '/tool-reference-upload',
  path: '/tool-reference-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecognizeRoute = ApiRecognizeRouteImport.update({
  id: '/api/recognize',
  path: '/api/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingReturnRoute = BillingReturnRouteImport.update({
  id: '/billing/return',
  path: '/billing/return',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecognitionsIndexRoute = AdminRecognitionsIndexRouteImport.update({
  id: '/recognitions/',
  path: '/recognitions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecognitionsAttemptIdRoute =
  AdminRecognitionsAttemptIdRouteImport.update({
    id: '/recognitions/$attemptId',
    path: '/recognitions/$attemptId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCatalogRoute = ApiBillingCatalogRouteImport.update({
  id: '/api/billing/catalog',
  path: '/api/billing/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingOrderRoute = ApiBillingOrderRouteImport.update({
  id: '/api/billing/order',
  path: '/api/billing/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingOrdersRoute = ApiBillingOrdersRouteImport.update({
  id: '/api/billing/orders',
  path: '/api/billing/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingReconcileRoute = ApiBillingReconcileRouteImport.update({
  id: '/api/billing/reconcile',
  path: '/api/billing/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecognitionStatusRoute = ApiRecognitionStatusRouteImport.update({
  id: '/api/recognition/status',
  path: '/api/recognition/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewardsShareRoute = ApiRewardsShareRouteImport.update({
  id: '/api/rewards/share',
  path: '/api/rewards/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxSessionRoute = ApiSandboxSessionRouteImport.update({
  id: '/api/sandbox/session',
  path: '/api/sandbox/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokPocRoute = ApiTiktokPocRouteImport.update({
  id: '/api/tiktok/poc',
  path: '/api/tiktok/poc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokRecognizeRoute = ApiTiktokRecognizeRouteImport.update({
  id: '/api/tiktok/recognize',
  path: '/api/tiktok/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy-credits': typeof BuyCreditsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/billing/return': typeof BillingReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/recognitions/$attemptId': typeof AdminRecognitionsAttemptIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/billing/catalog': typeof ApiBillingCatalogRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/order': typeof ApiBillingOrderRoute
  '/api/billing/orders': typeof ApiBillingOrdersRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/recognition/status': typeof ApiRecognitionStatusRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/tiktok/poc': typeof ApiTiktokPocRoute
  '/api/tiktok/recognize': typeof ApiTiktokRecognizeRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/recognitions/': typeof AdminRecognitionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/buy-credits': typeof BuyCreditsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/billing/return': typeof BillingReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/recognitions/$attemptId': typeof AdminRecognitionsAttemptIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/billing/catalog': typeof ApiBillingCatalogRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/order': typeof ApiBillingOrderRoute
  '/api/billing/orders': typeof ApiBillingOrdersRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/recognition/status': typeof ApiRecognitionStatusRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/tiktok/poc': typeof ApiTiktokPocRoute
  '/api/tiktok/recognize': typeof ApiTiktokRecognizeRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/recognitions': typeof AdminRecognitionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/buy-credits': typeof BuyCreditsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/billing/return': typeof BillingReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/recognitions/$attemptId': typeof AdminRecognitionsAttemptIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/billing/catalog': typeof ApiBillingCatalogRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/order': typeof ApiBillingOrderRoute
  '/api/billing/orders': typeof ApiBillingOrdersRoute
  '/api/billing/reconcile': typeof ApiBillingReconcileRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/recognition/status': typeof ApiRecognitionStatusRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/tiktok/poc': typeof ApiTiktokPocRoute
  '/api/tiktok/recognize': typeof ApiTiktokRecognizeRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/recognitions/': typeof AdminRecognitionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/buy-credits'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/billing/return'
    | '/guides/$slug'
    | '/admin/'
    | '/guides/'
    | '/admin/orders/$orderId'
    | '/admin/recognitions/$attemptId'
    | '/admin/users/$userId'
    | '/api/admin/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/billing/catalog'
    | '/api/billing/checkout'
    | '/api/billing/order'
    | '/api/billing/orders'
    | '/api/billing/reconcile'
    | '/api/billing/webhook'
    | '/api/recognition/status'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/tiktok/poc'
    | '/api/tiktok/recognize'
    | '/admin/orders/'
    | '/admin/recognitions/'
    | '/admin/users/'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/buy-credits'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/billing/return'
    | '/guides/$slug'
    | '/admin'
    | '/guides'
    | '/admin/orders/$orderId'
    | '/admin/recognitions/$attemptId'
    | '/admin/users/$userId'
    | '/api/admin/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/billing/catalog'
    | '/api/billing/checkout'
    | '/api/billing/order'
    | '/api/billing/orders'
    | '/api/billing/reconcile'
    | '/api/billing/webhook'
    | '/api/recognition/status'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/tiktok/poc'
    | '/api/tiktok/recognize'
    | '/admin/orders'
    | '/admin/recognitions'
    | '/admin/users'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/buy-credits'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/billing/return'
    | '/guides/$slug'
    | '/admin/'
    | '/guides/'
    | '/admin/orders/$orderId'
    | '/admin/recognitions/$attemptId'
    | '/admin/users/$userId'
    | '/api/admin/$'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/billing/catalog'
    | '/api/billing/checkout'
    | '/api/billing/order'
    | '/api/billing/orders'
    | '/api/billing/reconcile'
    | '/api/billing/webhook'
    | '/api/recognition/status'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/tiktok/poc'
    | '/api/tiktok/recognize'
    | '/admin/orders/'
    | '/admin/recognitions/'
    | '/admin/users/'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuyCreditsRoute: typeof BuyCreditsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EarnCreditsRoute: typeof EarnCreditsRoute
  IdentifyRoute: typeof IdentifyRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TiktokSongFinderRoute: typeof TiktokSongFinderRoute
  ToolReferenceRoute: typeof ToolReferenceRoute
  ToolReferenceUploadRoute: typeof ToolReferenceUploadRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecognizeRoute: typeof ApiRecognizeRoute
  BillingReturnRoute: typeof BillingReturnRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiBillingCatalogRoute: typeof ApiBillingCatalogRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingOrderRoute: typeof ApiBillingOrderRoute
  ApiBillingOrdersRoute: typeof ApiBillingOrdersRoute
  ApiBillingReconcileRoute: typeof ApiBillingReconcileRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiRecognitionStatusRoute: typeof ApiRecognitionStatusRoute
  ApiRewardsShareRoute: typeof ApiRewardsShareRoute
  ApiSandboxSessionRoute: typeof ApiSandboxSessionRoute
  ApiTiktokPocRoute: typeof ApiTiktokPocRoute
  ApiTiktokRecognizeRoute: typeof ApiTiktokRecognizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-credits': {
      id: '/buy-credits'
      path: '/buy-credits'
      fullPath: '/buy-credits'
      preLoaderRoute: typeof BuyCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn-credits': {
      id: '/earn-credits'
      path: '/earn-credits'
      fullPath: '/earn-credits'
      preLoaderRoute: typeof EarnCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-song-finder': {
      id: '/tiktok-song-finder'
      path: '/tiktok-song-finder'
      fullPath: '/tiktok-song-finder'
      preLoaderRoute: typeof TiktokSongFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-reference': {
      id: '/tool-reference'
      path: '/tool-reference'
      fullPath: '/tool-reference'
      preLoaderRoute: typeof ToolReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-reference-upload': {
      id: '/tool-reference-upload'
      path: '/tool-reference-upload'
      fullPath: '/tool-reference-upload'
      preLoaderRoute: typeof ToolReferenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recognize': {
      id: '/api/recognize'
      path: '/api/recognize'
      fullPath: '/api/recognize'
      preLoaderRoute: typeof ApiRecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/return': {
      id: '/billing/return'
      path: '/billing/return'
      fullPath: '/billing/return'
      preLoaderRoute: typeof BillingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recognitions/': {
      id: '/admin/recognitions/'
      path: '/recognitions'
      fullPath: '/admin/recognitions/'
      preLoaderRoute: typeof AdminRecognitionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recognitions/$attemptId': {
      id: '/admin/recognitions/$attemptId'
      path: '/recognitions/$attemptId'
      fullPath: '/admin/recognitions/$attemptId'
      preLoaderRoute: typeof AdminRecognitionsAttemptIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/catalog': {
      id: '/api/billing/catalog'
      path: '/api/billing/catalog'
      fullPath: '/api/billing/catalog'
      preLoaderRoute: typeof ApiBillingCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/order': {
      id: '/api/billing/order'
      path: '/api/billing/order'
      fullPath: '/api/billing/order'
      preLoaderRoute: typeof ApiBillingOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/orders': {
      id: '/api/billing/orders'
      path: '/api/billing/orders'
      fullPath: '/api/billing/orders'
      preLoaderRoute: typeof ApiBillingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/reconcile': {
      id: '/api/billing/reconcile'
      path: '/api/billing/reconcile'
      fullPath: '/api/billing/reconcile'
      preLoaderRoute: typeof ApiBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recognition/status': {
      id: '/api/recognition/status'
      path: '/api/recognition/status'
      fullPath: '/api/recognition/status'
      preLoaderRoute: typeof ApiRecognitionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewards/share': {
      id: '/api/rewards/share'
      path: '/api/rewards/share'
      fullPath: '/api/rewards/share'
      preLoaderRoute: typeof ApiRewardsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox/session': {
      id: '/api/sandbox/session'
      path: '/api/sandbox/session'
      fullPath: '/api/sandbox/session'
      preLoaderRoute: typeof ApiSandboxSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok/poc': {
      id: '/api/tiktok/poc'
      path: '/api/tiktok/poc'
      fullPath: '/api/tiktok/poc'
      preLoaderRoute: typeof ApiTiktokPocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tiktok/recognize': {
      id: '/api/tiktok/recognize'
      path: '/api/tiktok/recognize'
      fullPath: '/api/tiktok/recognize'
      preLoaderRoute: typeof ApiTiktokRecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminRecognitionsAttemptIdRoute: typeof AdminRecognitionsAttemptIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminRecognitionsIndexRoute: typeof AdminRecognitionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminRecognitionsAttemptIdRoute: AdminRecognitionsAttemptIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminRecognitionsIndexRoute: AdminRecognitionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BuyCreditsRoute: BuyCreditsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EarnCreditsRoute: EarnCreditsRoute,
  IdentifyRoute: IdentifyRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TiktokSongFinderRoute: TiktokSongFinderRoute,
  ToolReferenceRoute: ToolReferenceRoute,
  ToolReferenceUploadRoute: ToolReferenceUploadRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecognizeRoute: ApiRecognizeRoute,
  BillingReturnRoute: BillingReturnRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiBillingCatalogRoute: ApiBillingCatalogRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingOrderRoute: ApiBillingOrderRoute,
  ApiBillingOrdersRoute: ApiBillingOrdersRoute,
  ApiBillingReconcileRoute: ApiBillingReconcileRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiRecognitionStatusRoute: ApiRecognitionStatusRoute,
  ApiRewardsShareRoute: ApiRewardsShareRoute,
  ApiSandboxSessionRoute: ApiSandboxSessionRoute,
  ApiTiktokPocRoute: ApiTiktokPocRoute,
  ApiTiktokRecognizeRoute: ApiTiktokRecognizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
