/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarnCreditsRouteImport } from './routes/earn-credits'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TiktokSongFinderRouteImport } from './routes/tiktok-song-finder'
import { Route as ToolReferenceRouteImport } from './routes/tool-reference'
import { Route as ToolReferenceUploadRouteImport } from './routes/tool-reference-upload'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiRecognizeRouteImport } from './routes/api.recognize'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiRewardsShareRouteImport } from './routes/api.rewards.share'
import { Route as ApiSandboxSessionRouteImport } from './routes/api.sandbox.session'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api.auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnCreditsRoute = EarnCreditsRouteImport.update({
  id: '/earn-credits',
  path: '/earn-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokSongFinderRoute = TiktokSongFinderRouteImport.update({
  id: '/tiktok-song-finder',
  path: '/tiktok-song-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolReferenceRoute = ToolReferenceRouteImport.update({
  id: '/tool-reference',
  path: '/tool-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolReferenceUploadRoute = ToolReferenceUploadRouteImport.update({
  id: '/tool-reference-upload',
  path: '/tool-reference-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecognizeRoute = ApiRecognizeRouteImport.update({
  id: '/api/recognize',
  path: '/api/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewardsShareRoute = ApiRewardsShareRouteImport.update({
  id: '/api/rewards/share',
  path: '/api/rewards/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxSessionRoute = ApiSandboxSessionRouteImport.update({
  id: '/api/sandbox/session',
  path: '/api/sandbox/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/earn-credits': typeof EarnCreditsRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-song-finder': typeof TiktokSongFinderRoute
  '/tool-reference': typeof ToolReferenceRoute
  '/tool-reference-upload': typeof ToolReferenceUploadRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recognize': typeof ApiRecognizeRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/rewards/share': typeof ApiRewardsShareRoute
  '/api/sandbox/session': typeof ApiSandboxSessionRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/guides/$slug'
    | '/guides/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/guides/$slug'
    | '/guides'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/contact'
    | '/dashboard'
    | '/earn-credits'
    | '/identify'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/tiktok-song-finder'
    | '/tool-reference'
    | '/tool-reference-upload'
    | '/api/health'
    | '/api/recognize'
    | '/guides/$slug'
    | '/guides/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/rewards/share'
    | '/api/sandbox/session'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EarnCreditsRoute: typeof EarnCreditsRoute
  IdentifyRoute: typeof IdentifyRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TiktokSongFinderRoute: typeof TiktokSongFinderRoute
  ToolReferenceRoute: typeof ToolReferenceRoute
  ToolReferenceUploadRoute: typeof ToolReferenceUploadRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecognizeRoute: typeof ApiRecognizeRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiRewardsShareRoute: typeof ApiRewardsShareRoute
  ApiSandboxSessionRoute: typeof ApiSandboxSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn-credits': {
      id: '/earn-credits'
      path: '/earn-credits'
      fullPath: '/earn-credits'
      preLoaderRoute: typeof EarnCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-song-finder': {
      id: '/tiktok-song-finder'
      path: '/tiktok-song-finder'
      fullPath: '/tiktok-song-finder'
      preLoaderRoute: typeof TiktokSongFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-reference': {
      id: '/tool-reference'
      path: '/tool-reference'
      fullPath: '/tool-reference'
      preLoaderRoute: typeof ToolReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-reference-upload': {
      id: '/tool-reference-upload'
      path: '/tool-reference-upload'
      fullPath: '/tool-reference-upload'
      preLoaderRoute: typeof ToolReferenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recognize': {
      id: '/api/recognize'
      path: '/api/recognize'
      fullPath: '/api/recognize'
      preLoaderRoute: typeof ApiRecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewards/share': {
      id: '/api/rewards/share'
      path: '/api/rewards/share'
      fullPath: '/api/rewards/share'
      preLoaderRoute: typeof ApiRewardsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandbox/session': {
      id: '/api/sandbox/session'
      path: '/api/sandbox/session'
      fullPath: '/api/sandbox/session'
      preLoaderRoute: typeof ApiSandboxSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EarnCreditsRoute: EarnCreditsRoute,
  IdentifyRoute: IdentifyRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TiktokSongFinderRoute: TiktokSongFinderRoute,
  ToolReferenceRoute: ToolReferenceRoute,
  ToolReferenceUploadRoute: ToolReferenceUploadRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecognizeRoute: ApiRecognizeRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiRewardsShareRoute: ApiRewardsShareRoute,
  ApiSandboxSessionRoute: ApiSandboxSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
